### PR TITLE
Add fee for QWC foundation

### PR DESCRIPTION
**Pull request by nnian**
`!WARNING! This is work in progress. Please, don't merge!`

In order to solve this https://voting.qwertycoin.org/?election=20 election work on a mining fee towards the qwertycoin foundation for creating funds to paying new exchanges, marketing stuff and other project related stuff.

### CODE REVIEW

**Comment by Xecute0101** [comment]
Will this be a soft or a hard fork?

**Comment by Xecute0101** [comment]
Can we please finalize this by the end of this year?

**Comment by exploshot** [comment]
In my eyes we can merge this.

**Comment by speqtr** [comment]
@exploshot, it looks like there is a conflicting file `lib/Global/version.h.in`. Could you, please, rebase this PR on top of latest commit from `master` branch before merging it?

**Comment by exploshot** [comment]
Can we merge and close? @nnian @speqtr 
Travis is only on fail because of 
```The job exceeded the maximum time limit for jobs, and has been terminated. ```
in macOS Debug

**Comment by nnian** [comment]
The tests are missing. And maybe in some other (core) classes?

**Comment by nnian** [comment]
@Xecute0101, @exploshot, @speqtr this PR can be merged once somebody see that all CI builds are green.

**Pull request merged**
