### PR TITLE
Fixed code style issues in lib/CryptoNoteCore dir

### PR DESCRIPTION
**Pull request by speqtr**
Fixed code style issues in `lib/CryptoNoteCore` folder.
For more details about code style changes see issue #67.

### CODE REVIEW

**Comment by speqtr** [comment]
**NOTE:** This is a _Work In Progress_. Please, **don't merge** until I post a comment "Done. Can be merged".

**Comment by speqtr** [comment]
@nnian please, restart the CI builds on Travis CI. Looks like one of the Linux builds failed due to a network issue (`apt-get` package manager related issue).

**Comment by nnian** [comment]
@speqtr macOS debug is building for the 3rd round now, hm

**Comment by speqtr** [comment]
Hmmm... Later today I will upload updated version of `lib/CryptoNoteCore`, let's see how it will compile with "macOS debug" configuration.

**Comment by speqtr** [comment]
Currently one test (`WalletLegacyApi.outcommingExternalTransactionTotalAmount`) is failing on macOS debug environment. I'll take a look and push a patch once fixed.

**Comment by speqtr** [comment]
Please, don't merge this PR. Latest build will be green because I temporary disabled tests in order to properly reset cache on all CI servers.

**Comment by Xecute0101** [comment]
If this pending issue is regarding the bulid-time on Travis-CI, then I suggest we merge unless there is a compilation failure on the debug mode. Or we upgrade Travis-CI to a paid service. IMO, we are losing more time and money from this type of optimization.

**Comment by speqtr** [comment]
@Xecute0101 we don't merge because some tests are failing. I'm working on fixing them.

**Comment by speqtr** [comment]
All regressions are fixed, all tests are passing without any errors.
@nnian this PR can be merged.

**Comment by nnian** [comment]
@speqtr good work :)

**Comment by speqtr** [comment]
@nnian thanks 🙂

**Pull request merged**
