### PR TITLE
Additional fixes for tests

### PR DESCRIPTION
**Pull request by speqtr**
`WARNING` Please, don't merge before you see my comment "Done. Can be merged!".

Goals of this PR:
1. Fix tests compilation/runtime for Windows;
2. Disable some tests to fit into Travis CI build time limitations.

### CODE REVIEW

**Comment by speqtr** [comment]
As a part of this PR I added tests command stub to AppVeyor CI script. Currently it searches for tests using regexp `NONE`, obviously doesn't find anything and skips tests on Windows. Once we handle "build time limitation" issue

**Comment by Xecute0101** [comment]
Could paid Travis CI account solve this issue?

**Comment by speqtr** [comment]
> Could paid Travis CI account solve this issue?

Yes, all paid Travis CI plans include unlimited build minutes.
More info can be found here: https://travis-ci.com/plans

**Comment by speqtr** [comment]
**UPDATE**

Latest improvements:
- better android platform detection, there is no more need to specify `-DANDROID` manually if android toolchain file is used;
- fixed compilation issues in `tests` dir for Android platform;
- on Travis CI and AppVeyor CI tests are now compiled on all platforms (including Android and Windows);

PS: Builds are temproray failing due to some bug in Travis CI configuration. Fix is coming soon.

**Comment by speqtr** [comment]
UPDATE: Issue with Travis CI is fixed. Waiting for builds to compile now.

**Comment by speqtr** [comment]
**UPDATE:** After latest build on Travis CI I collected logs for Linux and macOS and will look for tests that are taking the most of time. I will disable those tests temporarly until we resolve issue with tests performance and Travis CI / AppVeyor build time limitations.

**Comment by nnian** [comment]
Hi @speqtr 
When your PR is ready we will release new packages. It looks like the travis debug is now bug free right?

**Comment by Xecute0101** [comment]
@speqtr @nnian 
What do you think about enabling test for only linux build with a paid subscription?

**Comment by speqtr** [comment]
@nnian My PR will be ready for merge until the end of this day. I'll apply a small fix and push it in a couple of hours.

**Comment by speqtr** [comment]
**UPDATE** Disabled some extremely long running tests. Will see in about 30-40 minutes if that is enough for free Travis CI plan.

**Comment by speqtr** [comment]
It looks like latest Travis CI configuration runs fast enough to fit into build time limitation.

@nnian This PR can be merged once AppVeyor build completes.

**Pull request merged**
