### PR TITLE
Fixed code style issues in 'include' dir

### PR DESCRIPTION
**Pull request by speqtr**
Fixed code style issues in `include` dir.
For more details about code style changes see issue #67.

### CODE REVIEW

**Comment by speqtr** [comment]
This PR temporary disables tests on Travis CI. I will re-enable tests within the scope of this PR once all builds on Travis CI will complete (and reset their cache).

**Comment by speqtr** [comment]
First build completed succesfully. Now all build VMs on Travis CI should use previously saved dependencies cache in the subsequent builds. So I re-enabled tests on Travis CI.

**Comment by nnian** [comment]
@speqtr ready to merge?

**Comment by speqtr** [comment]
@nnian yes 🙂

**Pull request merged**
