### PR TITLE
Improve application constants management

### PR DESCRIPTION
**Pull request by speqtr**
For more details please refer to issue #96.

### CODE REVIEW

**Comment by nnian** [comment]
Hi, i've compiled your fork on a fresh Windows 64 Pro VM and tried to start qwertycoind.exe and got the following error:

```
2019-Aug-13 01:50:17.959764 INFO    Program Working Directory: qwertycoind.exe
2019-Aug-13 01:50:18.007027 INFO    Initializing p2p server...
[...]
2019-Aug-13 01:50:21.294113 INFO    Mining has been stopped, 0 finished
SwappedVector cache hits: 0, misses: 0 (-nan(ind)%)
2019-Aug-13 01:50:21.298732 ERROR   Exception: SwappedVector::operator[]
```

But I have heard that this error sometimes occurs in version 5.2.0 without your changes. :anguished:
Now i try it with snapshot Blockchain. (Above errors happens when the daemon wants to create the blocks.bin file for the first time) .

**Comment by Xecute0101** [comment]
This does not happen on Linux?

**Comment by speqtr** [comment]
@nnian what are the steps to reproduce the issue? Does it occur constantly or randomly? On all platforms or only on Windows?

**Comment by Xecute0101** [comment]
@speqtr I know it happens on Windows 100% if bin files are not present from previous operation. blockindex and block.bin files are at 0 or 1kb and swapped vector error[] will be saved in the log file.

**Comment by speqtr** [comment]
> I know it happens on Windows 100% if bin files are not present from previous operation. blockindex and block.bin files are at 0 or 1kb and swapped vector error[] will be saved in the log file.

Does it happen only with version compiled from this PR. Or previous versions are also affected?

**Comment by Xecute0101** [comment]
5.1.4 -> 5.2.0 ->5.2.1 is the official release order. Issues were reported from 5.2.0

**Comment by speqtr** [comment]
OK, so it was not caused by this PR. Here is what (I think) we need to do:
1. Review and merge this PR;
2. Re-enable auto tests on Travis CI (@exploshot disabled them for some reason);
3. Open a new issue for `ERROR   Exception: SwappedVector::operator[]` error and fix it.

**Comment by nnian** [comment]
Good Morning Guys,
now i tried this fork using a Snapshot on my PC to avoit that SwappedVector Issue and got the following behaviors:

```
2019-Aug-13 11:01:38.984871 INFO    CHECKPOINT PASSED FOR HEIGHT 384404 901f0554bef3fb0befa023650622377a6d48902fa76c076537aebcd72f48a4d3
2019-Aug-13 11:01:40.143100 INFO    Checking block version at 40001
2019-Aug-13 11:01:40.146982 INFO    Checking block version at 46001
2019-Aug-13 11:01:40.150944 INFO    Checking block version at 110521
2019-Aug-13 11:01:40.153938 INFO    Checking block version at 250721
2019-Aug-13 11:01:40.156928 INFO    Blockchain initialized. last block: 384422, d4.h12.m24.s11 time ago, current difficulty: 71153791627
2019-Aug-13 11:01:40.165931 INFO    Core initialized OK
2019-Aug-13 11:01:40.169921 INFO    Starting core rpc server on address 127.0.0.1:8197
2019-Aug-13 11:01:40.173910 INFO    Core rpc server started ok
2019-Aug-13 11:01:40.176483 INFO    Starting p2p net loop...
2019-Aug-13 11:01:40.178477 INFO    Starting node_server
2019-Aug-13 11:01:50.327087 INFO    [RANDOM_IP_ANONYMIZED:8196 OUT] Sync data returned unknown top block: 384422 -> 387657 [3235 blocks (4 days) behind]
2019-Aug-13 11:01:50.327087 INFO    SYNCHRONIZATION started
2019-Aug-13 11:01:50.430335 INFO    [RANDOM_IP_ANONYMIZED:8196 OUT] Sync data returned unknown top block: 384422 -> 387657 [3235 blocks (4 days) behind]
2019-Aug-13 11:01:50.430335 INFO    SYNCHRONIZATION started
2019-Aug-13 11:01:58.287696 INFO    [RANDOM_IP_ANONYMIZED:8196 OUT] Sync data returned unknown top block: 384456 -> 387657 [3201 blocks (4 days) behind]
2019-Aug-13 11:01:58.287696 INFO    SYNCHRONIZATION started
2019-Aug-13 11:02:05.536491 INFO    [RANDOM_IP_ANONYMIZED:8196 OUT] Sync data returned unknown top block: 384479 -> 387657 [3178 blocks (4 days) behind]
2019-Aug-13 11:02:05.536491 INFO    SYNCHRONIZATION started
2019-Aug-13 11:02:15.414617 INFO    [RANDOM_IP_ANONYMIZED:8196 OUT] Sync data returned unknown top block: 384530 -> 387657 [3127 blocks (4 days) behind]
2019-Aug-13 11:02:15.414617 INFO    SYNCHRONIZATION started
2019-Aug-13 11:02:50.344545 INFO    [RANDOM_IP_ANONYMIZED:19950 OUT] Sync data returned unknown top block: 384550 -> 387657 [3107 blocks (4 days) behind]
2019-Aug-13 11:02:50.344545 INFO    SYNCHRONIZATION started
2019-Aug-13 11:03:01.834652 INFO    [RANDOM_IP_ANONYMIZED:8196 OUT] Sync data returned unknown top block: 384599 -> 387657 [3058 blocks (4 days) behind]
2019-Aug-13 11:03:01.834652 INFO    SYNCHRONIZATION started
```

During synchronization, the daemon crashes and needs to be restarted. I can't test it on other OS atm but i think this should happens on every OS. This [Snapshot](https://blockchain.qwertycoin.org/snapshot_2019-08-12.tar.gz)  i used.

**Comment by speqtr** [comment]
@nnian Did you perform the same test with 5.2.0?

**Comment by speqtr** [comment]
So latest commited master (5.2.1) works without errors?

`Qwertycoin::Constants::nullHash()` and `Qwertycoin::Constants::nullPublicKey()` have identical values as `NULL_HASH` and `NULL_PUBLIC_KEY` that were used previously. Could you please tell me what exactly did you insert in the old configuration file and where?

**Comment by Xecute0101** [comment]
This is what happens with the latest Windows 10 Pro without previous blockchain files. It tries to generate blockindexes.bin and blocks.bin files but crashes.

[qwertycoind 5.2.1 without blockchain files.log](https://github.com/qwertycoin-org/qwertycoin/files/3496470/qwertycoind.5.2.1.without.blockchain.files.log)

**Comment by Xecute0101** [comment]
This is what happens with Qwertycoin v5.2.1.3090 (ae662d8) on the latest Windows 10 Pro with previous blockchain files. It works without any issues.

[qwertycoind 5.2.1 with blockchain files.log](https://github.com/qwertycoin-org/qwertycoin/files/3496493/qwertycoind.5.2.1.with.blockchain.files.log)

**Comment by Xecute0101** [comment]
Like Speqtr proposed, let's merge this PR and issue a new one for the vector issue.

**Comment by who-biz** [comment]
FWIW, I think that some better management of those precompile constants in `security/config/cryptonote_config.h` is a very good move to make.

I just discussed this with Xecute, but I recently discovered that unlock time is not checked by consensus whatsoever (in Blur, Monero, and likely QWC, as well). This is due to the fact that `CRYPTONOTE_DEFAULT_TX_SPENDABLE_AGE` is defined as a pre-compile constant.   One can set the value to `0` as a result, and the the transaction will go through, regardless of the fact that it is well below the defined `60` blocks.

**Comment by who-biz** [comment]
See discussion here, for unlock time specifics: https://github.com/monero-project/monero/issues/5712

**Comment by who-biz** [comment]
> @speqtr I know it happens on Windows 100% if bin files are not present from previous operation. blockindex and block.bin files are at 0 or 1kb and swapped vector error[] will be saved in the log file.
> 
> It is not from this update. After 5.1.4, we started to see this problem. 5.1.4 works fine.

This was what I experienced as well, when merging the changes from master branch into the LMDB repository.  I fixed the issue, by reverting to 5.1.4.  

It is probably helpful to note that the error does not occur if the blockchain has already begun syncing on a prior attempt.  So the error appears to only occur when syncing from 0.

**Comment by nnian** [comment]
> 
> 
> Like Speqtr proposed, let's merge this PR and issue a new one for the vector issue.

But it does not work properly (on my test devices). I can't start the daemon. @exploshot did you test this fork yet?

**Comment by speqtr** [comment]
> But it does not work properly (on my test devices). I can't start the daemon.

Isn't this related to the `ERROR Exception: SwappedVector::operator[]` error?

**Comment by nnian** [comment]
> 
> 
> > But it does not work properly (on my test devices). I can't start the daemon.
> 
> Isn't this related to the `ERROR Exception: SwappedVector::operator[]` error?

No. I start the qwertycoind.exe wait for the synchronization process and the daemon crashes instantly without any error messages.

**Comment by speqtr** [comment]
Hmmm... I didn't run into similar issues. But I'll look into it tomorrow.

**Comment by nnian** [comment]
> 
> 
> So latest commited master (5.2.1) works without errors?
> 
> `Qwertycoin::Constants::nullHash()` and `Qwertycoin::Constants::nullPublicKey()` have identical values as `NULL_HASH` and `NULL_PUBLIC_KEY` that were used previously. Could you please tell me what exactly did you insert in the old configuration file and where?

i mean that i never used https://github.com/speqtr/fork-qwertycoin-org-qwertycoin/blob/master/lib/Global/Constants.cpp#L63

`nullHash`, `nullPublicKey` or `nullSecretKey`
These values were taken over, forgotten to use and then not deleted. But do the values agree with the old ones, which now use these constants?

On Ubuntu your fork version can synchronize from snapshot to current Network height without any Problem. But on my Windows Device it crashed after a few synchronized Blocks and crashes without any message.

```
2019-Aug-14 09:08:59.045795 INFO    CHECKPOINT PASSED FOR HEIGHT 384404 901f0554bef3fb0befa023650622377a6d48902fa76c076537aebcd72f48a4d3
2019-Aug-14 09:09:00.249602 INFO    Checking block version at 40001
2019-Aug-14 09:09:00.253576 INFO    Checking block version at 46001
2019-Aug-14 09:09:00.256559 INFO    Checking block version at 110521
2019-Aug-14 09:09:00.259549 INFO    Checking block version at 250721
2019-Aug-14 09:09:00.261544 INFO    Blockchain initialized. last block: 387681, d0.h21.m30.s10 time ago, current difficulty: 101920783368
2019-Aug-14 09:09:00.265533 INFO    Core initialized OK
2019-Aug-14 09:09:00.269522 INFO    Starting core rpc server on address 127.0.0.1:8197
2019-Aug-14 09:09:00.272515 INFO    Core rpc server started ok
2019-Aug-14 09:09:00.275508 INFO    Starting p2p net loop...
2019-Aug-14 09:09:00.277502 INFO    Starting node_server
2019-Aug-14 09:09:25.455778 INFO    [IP:8196 OUT] Sync data returned unknown top block: 387681 -> 388306 [625 blocks (0 days) behind]
2019-Aug-14 09:09:25.455778 INFO    SYNCHRONIZATION started
2019-Aug-14 09:09:37.907293 INFO    [IP:8196 OUT] Sync data returned unknown top block: 387715 -> 388306 [591 blocks (0 days) behind]
2019-Aug-14 09:09:37.907293 INFO    SYNCHRONIZATION started
2019-Aug-14 09:09:40.715785 INFO    [IP:8196 OUT] Sync data returned unknown top block: 387729 -> 388306 [577 blocks (0 days) behind]
2019-Aug-14 09:09:40.715785 INFO    SYNCHRONIZATION started

D:\fork-qwertycoin-org-qwertycoin\build\src\Release>

**Comment by nnian** [comment]
If someone can successfully sync on a Windows device without the daemon crashing, we can merge this PR here and I'll take care of my problem later. @speqtr @exploshot @who-biz @Xecute0101 If anyone of you can confirm that this fork works successfully with Windows that would be great.

**Pull request merged**
