### PR TITLE
Fixed compilation issues in tests subdir

### PR DESCRIPTION
**Pull request by speqtr**
`WARNING` Work in progress. Please, don't merge.

**TODO:**
- [x] Update Hunter (package manager) to v0.23.155;
- [x] Fix `tests/CoreTests` compilation errors;
- [x] Fix `tests/UnitTests` compilation errors;
- [x] Remove outdated tests (`IntegrationTestLib`, `IntegrationTests` and `TransferTests`);
- [x] Fixed/disabled broken test cases in `CoreTests`;
- [x] Fixed/disabled broken test cases in `UnitTests`;
- [x] Fixed segfault in `DifficultyTests`;
- [x] Check all test cases and enable working test cases on CI builds;
- [x] Enabled parallel builds on Travis CI;
- [x] Enabled parallel testing on Travis CI;
- [x] Updated regexp for filtering log on Travis CI;
- [x] Updated code-coverage settings on Travis CI.

**Goals of this PR:**
1. Fix compilation errors in `tests` dir;
2. Temporary disable broken tests;
3. Start running all test targets with working tests on CI builds.

NOTE: In future PRs all broken tests will be fixed and re-enabled. This PRs aims to enable every test that works right now and make it as a some sort of "starting point" for future improvements of test cases.

### CODE REVIEW

**Comment by speqtr** [comment]
NOTE: I noticed multiple times in different PRs (including this one) that release build on macOS on Travis CI hangs and fails with a timeout error. This looks like Travis CI issue because simply restarting the build (with no changes) fixes the issue.

**Comment by Xecute0101** [comment]
Did we have cumulative difficulties in the past or is it a new feature?

**Comment by speqtr** [comment]
Right now it looks more like an "occasional timeout issue". Also it hangs only on `cpack` step on macOS, which simply creates `.zip` archive with artifacts.

**Comment by speqtr** [comment]
**UPDATE:** I checked all the currently existing tests. Please, see report below.

Currently there are 11 test projects:
1. **CoreTests** `core_tests` (mostly OK, 10-15 broken tests; 210 sec);
2. **CryptoTests** `crypto_tests` (OK, 27 sec):
```
ctest -R CryptoTests --output-on-failure
Test project /home/vagrant/.tmp/build
    Start 2: CryptoTests
1/1 Test #2: CryptoTests ......................   Passed   26.36 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =  26.36 sec
```
3. **DifficultyTests** `difficulty_tests` (broken):
```
ctest -R DifficultyTests --output-on-failure
Test project /home/vagrant/.tmp/build
    Start 3: DifficultyTests
1/1 Test #3: DifficultyTests ..................***Exception: SegFault  0.13 sec


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.13 sec

The following tests FAILED:
	  3 - DifficultyTests (SEGFAULT)
Errors while running CTest
```
4. **HashTargetTests** `hash_target_tests` (OK, 1 sec):
```
ctest -R HashTargetTests --output-on-failure
Test project /home/vagrant/.tmp/build
    Start 4: HashTargetTests
1/1 Test #4: HashTargetTests ..................   Passed    0.10 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.10 sec
```
5. **HashTests-*** `hash_tests` (OK, 1 sec):
```
ctest -R HashTests-* --output-on-failure
Test project /home/vagrant/.tmp/build
    Start  5: HashTests-extra-blake
1/7 Test  #5: HashTests-extra-blake ............   Passed    0.02 sec
    Start  6: HashTests-extra-groestl
2/7 Test  #6: HashTests-extra-groestl ..........   Passed    0.04 sec
    Start  7: HashTests-extra-jh
3/7 Test  #7: HashTests-extra-jh ...............   Passed    0.04 sec
    Start  8: HashTests-extra-skein
4/7 Test  #8: HashTests-extra-skein ............   Passed    0.02 sec
    Start  9: HashTests-fast
5/7 Test  #9: HashTests-fast ...................   Passed    0.03 sec
    Start 10: HashTests-slow
6/7 Test #10: HashTests-slow ...................   Passed    0.19 sec
    Start 11: HashTests-tree
7/7 Test #11: HashTests-tree ...................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) =   0.34 sec
```
6. **IntegrationTests** `integration_tests` (broken and were never enabled):
```
...
2019-Apr-22 14:11:35.288840 DEBUG   [BlockchainSynchronizer] Blocks added to consumers
2019-Apr-22 14:11:35.288951 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 14:11:35.289079 DEBUG   [BlockchainSynchronizer] Starting blockchain synchronization...
2019-Apr-22 14:11:35.289141 DEBUG   [BlockchainSynchronizer] Shortest chain size 5
2019-Apr-22 14:11:35.289197 DEBUG   [BlockchainSynchronizer] Common history: start block index 0, sparse chain size 5
2019-Apr-22 14:11:35.290521 DEBUG   [BlockchainSynchronizer] Blocks received, start index 3, count 2
2019-Apr-22 14:11:35.290639 DEBUG   [BlockchainSynchronizer] Process blocks, start index 3, count 2
2019-Apr-22 14:11:35.291659 DEBUG   [BlockchainSynchronizer] Adding blocks to consumer, consumer 0x555610a967e0, start index 4, count 1
2019-Apr-22 14:11:35.292991 DEBUG   [BlockchainSynchronizer] Blocks received, start index 4, count 1
2019-Apr-22 14:11:35.293201 DEBUG   [BlockchainSynchronizer] Process blocks, start index 4, count 1
2019-Apr-22 14:11:35.293772 DEBUG   [BlockchainSynchronizer] No new blocks received. Consumers not updated
2019-Apr-22 14:11:35.293875 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 14:11:35.294102 DEBUG   [BlockchainSynchronizer] Starting pool synchronization...
2019-Apr-22 14:11:35.294327 DEBUG   [BlockchainSynchronizer] Pool union size 0, intersection size 0
2019-Apr-22 14:11:35.295337 DEBUG   [BlockchainSynchronizer] Transaction pool changes received, added 0, deleted 0
2019-Apr-22 14:11:35.295413 DEBUG   [BlockchainSynchronizer] Starting to process pool transactions, added 0:{}, deleted 0:{}
2019-Apr-22 14:11:35.295470 DEBUG   [BlockchainSynchronizer] Pool changes processed
2019-Apr-22 14:11:35.295535 DEBUG   [BlockchainSynchronizer] Idle
2019-Apr-22 14:11:35.317934 DEBUG   [BlockchainSynchronizer] Blocks added to consumers
2019-Apr-22 14:11:35.318176 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 14:11:35.318480 DEBUG   [BlockchainSynchronizer] Starting blockchain synchronization...
2019-Apr-22 14:11:35.318877 DEBUG   [BlockchainSynchronizer] Shortest chain size 5
2019-Apr-22 14:11:35.319000 DEBUG   [BlockchainSynchronizer] Common history: start block index 0, sparse chain size 5
2019-Apr-22 14:11:35.320502 DEBUG   [BlockchainSynchronizer] Blocks received, start index 4, count 1
2019-Apr-22 14:11:35.320747 DEBUG   [BlockchainSynchronizer] Process blocks, start index 4, count 1
2019-Apr-22 14:11:35.321241 DEBUG   [BlockchainSynchronizer] No new blocks received. Consumers not updated
2019-Apr-22 14:11:35.321633 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 14:11:35.321729 DEBUG   [BlockchainSynchronizer] Starting pool synchronization...
2019-Apr-22 14:11:35.321802 DEBUG   [BlockchainSynchronizer] Pool union size 0, intersection size 0
2019-Apr-22 14:11:35.323134 DEBUG   [BlockchainSynchronizer] Transaction pool changes received, added 0, deleted 0
2019-Apr-22 14:11:35.323265 DEBUG   [BlockchainSynchronizer] Starting to process pool transactions, added 0:{}, deleted 0:{}
2019-Apr-22 14:11:35.323341 DEBUG   [BlockchainSynchronizer] Pool changes processed
2019-Apr-22 14:11:35.323473 DEBUG   [BlockchainSynchronizer] Idle <<-- HANGS AT THIS STEP!
```
7. **NodeRpcProxyTests** `node_rpc_proxy_tests` (looks like OK, but actually fails; 75 sec):
```
ctest -R NodeRpcProxyTests --output-on-failure
Test project /home/vagrant/.tmp/build
    Start 13: NodeRpcProxyTests
1/1 Test #13: NodeRpcProxyTests ................   Passed   75.04 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =  75.04 sec
```
8. **PerformanceTests** `performance_tests` (OK, were never enabled; 101 sec):
```
PerformanceTests:
Warm up: 2163 ms
test_construct_tx<1, 1> - OK:
  loop count:    100
  elapsed:       335 ms
  time per call: 3 ms/call

Warm up: 2168 ms
test_construct_tx<1, 2> - OK:
  loop count:    100
  elapsed:       402 ms
  time per call: 4 ms/call

Warm up: 2155 ms
test_construct_tx<1, 10> - OK:
  loop count:    100
  elapsed:       920 ms
  time per call: 9 ms/call

Warm up: 2161 ms
test_construct_tx<1, 100> - OK:
  loop count:    10
  elapsed:       676 ms
  time per call: 67 ms/call

Warm up: 2289 ms
test_construct_tx<1, 1000> - OK:
  loop count:    10
  elapsed:       6983 ms
  time per call: 698 ms/call

Warm up: 2476 ms
test_construct_tx<2, 1> - OK:
  loop count:    100
  elapsed:       478 ms
  time per call: 4 ms/call

Warm up: 2263 ms
test_construct_tx<2, 2> - OK:
  loop count:    100
  elapsed:       517 ms
  time per call: 5 ms/call

Warm up: 2376 ms
test_construct_tx<2, 10> - OK:
  loop count:    100
  elapsed:       1070 ms
  time per call: 10 ms/call

Warm up: 2279 ms
test_construct_tx<2, 100> - OK:
  loop count:    10
  elapsed:       689 ms
  time per call: 68 ms/call

Warm up: 2191 ms
test_construct_tx<10, 1> - OK:
  loop count:    100
  elapsed:       1274 ms
  time per call: 12 ms/call

Warm up: 2326 ms
test_construct_tx<10, 2> - OK:
  loop count:    100
  elapsed:       1336 ms
  time per call: 13 ms/call

Warm up: 2218 ms
test_construct_tx<10, 10> - OK:
  loop count:    100
  elapsed:       1823 ms
  time per call: 18 ms/call

Warm up: 2185 ms
test_construct_tx<10, 100> - OK:
  loop count:    10
  elapsed:       764 ms
  time per call: 76 ms/call

Warm up: 2186 ms
test_construct_tx<100, 1> - OK:
  loop count:    10
  elapsed:       936 ms
  time per call: 93 ms/call

Warm up: 2172 ms
test_construct_tx<100, 2> - OK:
  loop count:    10
  elapsed:       937 ms
  time per call: 93 ms/call

Warm up: 2154 ms
test_construct_tx<100, 10> - OK:
  loop count:    10
  elapsed:       980 ms
  time per call: 98 ms/call

Warm up: 2179 ms
test_construct_tx<100, 100> - OK:
  loop count:    10
  elapsed:       1576 ms
  time per call: 157 ms/call

Warm up: 2204 ms
test_check_ring_signature<1> - OK:
  loop count:    100
  elapsed:       97 ms
  time per call: 0 ms/call

Warm up: 2259 ms
test_check_ring_signature<2> - OK:
  loop count:    100
  elapsed:       196 ms
  time per call: 1 ms/call

Warm up: 2249 ms
test_check_ring_signature<10> - OK:
  loop count:    100
  elapsed:       908 ms
  time per call: 9 ms/call

Warm up: 2218 ms
test_check_ring_signature<100> - OK:
  loop count:    10
  elapsed:       922 ms
  time per call: 92 ms/call

Warm up: 2267 ms
test_is_out_to_acc - OK:
  loop count:    1000
  elapsed:       693 ms
  time per call: 0 ms/call

Warm up: 2284 ms
test_generate_key_image_helper - OK:
  loop count:    500
  elapsed:       607 ms
  time per call: 1 ms/call

Warm up: 2241 ms
test_generate_key_derivation - OK:
  loop count:    1000
  elapsed:       468 ms
  time per call: 0 ms/call

Warm up: 2193 ms
test_generate_key_image - OK:
  loop count:    1000
  elapsed:       493 ms
  time per call: 0 ms/call

Warm up: 2188 ms
test_derive_public_key - OK:
  loop count:    1000
  elapsed:       190 ms
  time per call: 0 ms/call

Warm up: 2207 ms
test_derive_secret_key - OK:
  loop count:    1000000
  elapsed:       11440 ms
  time per call: 0 ms/call

Warm up: 2216 ms
test_cn_slow_hash - OK:
  loop count:    10
  elapsed:       502 ms
  time per call: 50 ms/call

Tests finished. Elapsed time: 101 sec
```
9. **SystemTests** `system_tests` (OK, 9 sec):
```
ctest -R SystemTests --output-on-failure
Test project /home/vagrant/.tmp/build
    Start 14: SystemTests
1/1 Test #14: SystemTests ......................   Passed    8.59 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   8.59 sec
```
10. **TransfersTests** `transfers_tests` (seems OK, but miner process hangs, were never enabled before):
```
[==========] Running 3 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 1 test from NodeRpcProxyTest
[ RUN      ] NodeRpcProxyTest.PoolChangedCalledWhenTxCame
2019-04-22T15:39:07[ DEBUG ]NodeRPCProxy on port 9200 initialized
2019-Apr-22 15:39:07.306134 INFO    [BlockchainSynchronizer] Consumer added, consumer 0x55ab2d534710, count 1
2019-Apr-22 15:39:07.306501 INFO    [BlockchainSynchronizer] Starting...
2019-04-22T15:39:07[ DEBUG ]NodeRPCProxy on port 9200 initialized
2019-Apr-22 15:39:07.307505 DEBUG   [BlockchainSynchronizer] Working thread started
2019-Apr-22 15:39:07.307638 INFO    [BlockchainSynchronizer] Removing outdated pool transactions...
2019-Apr-22 15:39:07.307722 DEBUG   [BlockchainSynchronizer] Pool union size 0, intersection size 0
2019-04-22T15:39:07[ DEBUG ]NodeRPCProxy on port 9201 initialized
2019-Apr-22 15:39:07.308648 DEBUG   [BlockchainSynchronizer] Event: lastKnownBlockHeightUpdated 4
2019-Apr-22 15:39:07.309225 INFO    [BlockchainSynchronizer] Consumer added, consumer 0x55ab2d53a600, count 1
2019-Apr-22 15:39:07.310118 INFO    [BlockchainSynchronizer] Starting...
2019-Apr-22 15:39:07.310648 DEBUG   [BlockchainSynchronizer] Working thread started
2019-Apr-22 15:39:07.310987 INFO    [BlockchainSynchronizer] Removing outdated pool transactions...
2019-Apr-22 15:39:07.311441 DEBUG   [BlockchainSynchronizer] Event: lastKnownBlockHeightUpdated 4
2019-Apr-22 15:39:07.309872 DEBUG   [BlockchainSynchronizer] Outdated pool transactions received, 0:{}
2019-Apr-22 15:39:07.311715 INFO    [BlockchainSynchronizer] Outdated pool transactions processed
2019-Apr-22 15:39:07.311777 DEBUG   [BlockchainSynchronizer] Starting blockchain synchronization...
2019-Apr-22 15:39:07.311841 DEBUG   [BlockchainSynchronizer] Shortest chain size 1
2019-Apr-22 15:39:07.311955 DEBUG   [BlockchainSynchronizer] Common history: start block index 0, sparse chain size 1
2019-Apr-22 15:39:07.312202 DEBUG   [BlockchainSynchronizer] Pool union size 0, intersection size 0
2019-Apr-22 15:39:07.314929 DEBUG   [BlockchainSynchronizer] Outdated pool transactions received, 0:{}
2019-Apr-22 15:39:07.315311 INFO    [BlockchainSynchronizer] Outdated pool transactions processed
2019-Apr-22 15:39:07.315739 DEBUG   [BlockchainSynchronizer] Starting blockchain synchronization...
2019-Apr-22 15:39:07.316126 DEBUG   [BlockchainSynchronizer] Shortest chain size 1
2019-Apr-22 15:39:07.316573 DEBUG   [BlockchainSynchronizer] Common history: start block index 0, sparse chain size 1
2019-Apr-22 15:39:07.358200 DEBUG   [BlockchainSynchronizer] Blocks received, start index 0, count 5
2019-Apr-22 15:39:07.358324 DEBUG   [BlockchainSynchronizer] Process blocks, start index 0, count 5
2019-Apr-22 15:39:07.359355 DEBUG   [BlockchainSynchronizer] Adding blocks to consumer, consumer 0x55ab2d534710, start index 1, count 4
2019-Apr-22 15:39:07.362006 DEBUG   [BlockchainSynchronizer] Blocks received, start index 0, count 5
2019-Apr-22 15:39:07.362083 DEBUG   [BlockchainSynchronizer] Process blocks, start index 0, count 5
2019-Apr-22 15:39:07.363504 DEBUG   [BlockchainSynchronizer] Adding blocks to consumer, consumer 0x55ab2d53a600, start index 1, count 4
2019-Apr-22 15:39:07.377554 DEBUG   [BlockchainSynchronizer] Blocks added to consumers
2019-Apr-22 15:39:07.377901 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 15:39:07.378020 DEBUG   [BlockchainSynchronizer] Starting blockchain synchronization...
2019-Apr-22 15:39:07.378098 DEBUG   [BlockchainSynchronizer] Shortest chain size 5
2019-Apr-22 15:39:07.378161 DEBUG   [BlockchainSynchronizer] Common history: start block index 0, sparse chain size 5
2019-Apr-22 15:39:07.379915 DEBUG   [BlockchainSynchronizer] Blocks received, start index 4, count 1
2019-Apr-22 15:39:07.380015 DEBUG   [BlockchainSynchronizer] Process blocks, start index 4, count 1
2019-Apr-22 15:39:07.380304 DEBUG   [BlockchainSynchronizer] No new blocks received. Consumers not updated
2019-Apr-22 15:39:07.380389 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 15:39:07.380453 DEBUG   [BlockchainSynchronizer] Starting pool synchronization...
2019-Apr-22 15:39:07.380505 DEBUG   [BlockchainSynchronizer] Pool union size 0, intersection size 0
2019-Apr-22 15:39:07.381283 DEBUG   [BlockchainSynchronizer] Transaction pool changes received, added 0, deleted 0
2019-Apr-22 15:39:07.381353 DEBUG   [BlockchainSynchronizer] Starting to process pool transactions, added 0:{}, deleted 0:{}
2019-Apr-22 15:39:07.381525 DEBUG   [BlockchainSynchronizer] Pool changes processed
2019-Apr-22 15:39:07.381853 DEBUG   [BlockchainSynchronizer] Blocks added to consumers
2019-Apr-22 15:39:07.382001 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 15:39:07.382085 INFO    [BlockchainSynchronizer] Consumer added, consumer 0x55ab2d53c410, count 1
2019-Apr-22 15:39:07.382195 DEBUG   [BlockchainSynchronizer] Starting blockc2h0ain s1ync9h-rAopnri-z2a2tion. .15.:
2019-Apr-22 15:39:07.382298 DEBUG   [BlockchainSynchronizer] Shortest chain size 5
2019-Apr-22 15:39:07.382363 DEBUG   [BlockchainSynchronizer] Common history: start block index 0, sparse chain size 5
2019-Apr-22 15:39:07.382485 DEBUG   [BlockchainSynchronizer] Idle
39:07.382202 INFO    [BlockchainSynchronizer] Starting...
2019-Apr-22 15:39:07.383165 DEBUG   [BlockchainSynchronizer] Working thread started
2019-Apr-22 15:39:07.383338 INFO    [BlockchainSynchronizer] Removing outdated pool transactions...
2019-Apr-22 15:39:07.383860 DEBUG   [BlockchainSynchronizer] Blocks received, start index 4, count 1
2019-Apr-22 15:39:07.383934 DEBUG   [BlockchainSynchronizer] Process blocks, start index 4, count 1
2019-Apr-22 15:39:07.384208 DEBUG   [BlockchainSynchronizer] No new blocks received. Consumers not updated
2019-Apr-22 15:39:07.384287 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 15:39:07.384413 DEBUG   [BlockchainSynchronizer] Starting pool synchronization...
2019-Apr-22 15:39:07.384597 DEBUG   [BlockchainSynchronizer] Pool union size 0, intersection size 0
2019-Apr-22 15:39:07.383755 DEBUG   [BlockchainSynchronizer] Pool union size 0, intersection size 0
2019-Apr-22 15:39:07.385098 DEBUG   [BlockchainSynchronizer] Transaction pool changes received, added 0, deleted 0
2019-Apr-22 15:39:07.385212 DEBUG   [BlockchainSynchronizer] Starting to process pool transactions, added 0:{}, deleted 0:{}
2019-Apr-22 15:39:07.385282 DEBUG   [BlockchainSynchronizer] Pool changes processed
2019-Apr-22 15:39:07.385815 DEBUG   [BlockchainSynchronizer] Idle
2019-Apr-22 15:39:07.386040 DEBUG   [BlockchainSynchronizer] Outdated pool transactions received, 0:{}
2019-Apr-22 15:39:07.386227 INFO    [BlockchainSynchronizer] Outdated pool transactions processed
2019-Apr-22 15:39:07.386277 DEBUG   [BlockchainSynchronizer] Starting blockchain synchronization...
2019-Apr-22 15:39:07.386644 DEBUG   [BlockchainSynchronizer] Shortest chain size 1
2019-Apr-22 15:39:07.387081 DEBUG   [BlockchainSynchronizer] Common history: start block index 0, sparse chain size 1
2019-Apr-22 15:39:07.434210 DEBUG   [BlockchainSynchronizer] Blocks received, start index 0, count 5
2019-Apr-22 15:39:07.434814 DEBUG   [BlockchainSynchronizer] Process blocks, start index 0, count 5
2019-Apr-22 15:39:07.436356 DEBUG   [BlockchainSynchronizer] Adding blocks to consumer, consumer 0x55ab2d53c410, start index 1, count 4
2019-Apr-22 15:39:07.446908 DEBUG   [BlockchainSynchronizer] Blocks added to consumers
2019-Apr-22 15:39:07.447385 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 15:39:07.447725 DEBUG   [BlockchainSynchronizer] Starting blockchain synchronization...
2019-Apr-22 15:39:07.447815 DEBUG   [BlockchainSynchronizer] Shortest chain size 5
2019-Apr-22 15:39:07.448031 DEBUG   [BlockchainSynchronizer] Common history: start block index 0, sparse chain size 5
2019-Apr-22 15:39:07.449376 DEBUG   [BlockchainSynchronizer] Blocks received, start index 4, count 1
2019-Apr-22 15:39:07.449501 DEBUG   [BlockchainSynchronizer] Process blocks, start index 4, count 1
2019-Apr-22 15:39:07.450042 DEBUG   [BlockchainSynchronizer] No new blocks received. Consumers not updated
2019-Apr-22 15:39:07.450110 DEBUG   [BlockchainSynchronizer] Last block hash 7c75e28eacf57a08a8c5a1ad0eb607518761356a91a3b4e67bc001b7eb9d254c
2019-Apr-22 15:39:07.450329 DEBUG   [BlockchainSynchronizer] Starting pool synchronization...
2019-Apr-22 15:39:07.450798 DEBUG   [BlockchainSynchronizer] Pool union size 0, intersection size 0
2019-Apr-22 15:39:07.451568 DEBUG   [BlockchainSynchronizer] Transaction pool changes received, added 0, deleted 0
2019-Apr-22 15:39:07.451697 DEBUG   [BlockchainSynchronizer] Starting to process pool transactions, added 0:{}, deleted 0:{}
2019-Apr-22 15:39:07.451936 DEBUG   [BlockchainSynchronizer] Pool changes processed
2019-Apr-22 15:39:07.452332 DEBUG   [BlockchainSynchronizer] Idle
2019-Apr-22 15:39:07.553571 INFO    [BlockchainSynchronizer] Stopping...
2019-Apr-22 15:39:07.553794 DEBUG   [BlockchainSynchronizer] Resume
2019-Apr-22 15:39:07.553901 DEBUG   [BlockchainSynchronizer] Working thread stopped
2019-Apr-22 15:39:07.554145 INFO    [BlockchainSynchronizer] Stopped
2019-Apr-22 15:39:07.554283 INFO    [BlockchainSynchronizer] Stopping...
2019-Apr-22 15:39:07.554395 INFO    [BlockchainSynchronizer] Stopped
2019-Apr-22 15:39:07.554494 INFO    [BlockchainSynchronizer] Consumer removed, consumer 0x55ab2d53c410, count 0
2019-Apr-22 15:39:07.554619 INFO    [BlockchainSynchronizer] Stopping...
2019-Apr-22 15:39:07.555312 INFO    [BlockchainSynchronizer] Stopped
2019-Apr-22 15:39:07.655816 INFO    [BlockchainSynchronizer] Stopping...
2019-Apr-22 15:39:07.656170 DEBUG   [BlockchainSynchronizer] Resume
2019-Apr-22 15:39:07.656314 DEBUG   [BlockchainSynchronizer] Working thread stopped
2019-Apr-22 15:39:07.656611 INFO    [BlockchainSynchronizer] Stopped
2019-Apr-22 15:39:07.656886 INFO    [BlockchainSynchronizer] Stopping...
2019-Apr-22 15:39:07.657654 INFO    [BlockchainSynchronizer] Stopped
2019-Apr-22 15:39:07.658097 INFO    [BlockchainSynchronizer] Consumer removed, consumer 0x55ab2d53a600, count 0
2019-Apr-22 15:39:07.658249 INFO    [BlockchainSynchronizer] Stopping...
2019-Apr-22 15:39:07.658783 INFO    [BlockchainSynchronizer] Stopped <<-- HANGS AT THIS STEP!
```
11. **UnitTests** `unit_tests` (mostly OK, 20 broken tests; 227 sec).

NOTE1: Multiple tests were never enabled before (never regestered as tests cases), so I'm assuming no one run those tests for a very long time.

NOTE2: Some of the tests don't use `Boost.Tests` and/or `GTest`, implemented as executables with custom output. This should be fixed in order to be able to do code-coverage for those tests and properly catch/handle errors with `ctest` tool.

NOTE3: After looking inside tests implementation I didn't see any particular reason to use both Boost.Test and GTest libraries in the project. So I think we should consider switching to use only one of those two testing libraries (prefferably Boost.Tests).

**Comment by Qwertycoin** [comment]
> 
> 
> Also I did notice in test config files that "bytecoind.exe" is used as a name of the daemon tool, so I'm assuming that those tests were never used for `qwertycoin` code base because they would simply fail due to incorrect tool name.

Yes we never used the IntegrationTests before. This bytecoind.exe is a relict from the fork from the fork.... fork fork.

**Comment by speqtr** [comment]
@qwertycoin-org 
> Yes we never used the IntegrationTestLib before. This bytecoind.exe is a relict from the fork from the fork.... fork fork.

In this case... Do I need to fix and re-enable those tests? Or should I just remove them?

NOTE: It looks like at least bytecoin and monero removed `IntegrationTestLib` and `IntegrationTests` from their project long time ago.

**Comment by Qwertycoin** [comment]
I do not think we need the IntegrationTestLib. I would just suggest doing what is easiest / fastest. I do not see a need / an effort for this test.

**Comment by speqtr** [comment]
@qwertycoin-org Please, note that removing `IntegrationTestLib` will result in removing `QwertycoinTests::IntegrationTests` and `QwertycoinTests::TransfersTests`, because both of those targets depend on `IntegrationTestLib`.

But it looks like all the three targets aren't functional at the moment. So the easiest solution would be to simply remove them.

**Comment by Qwertycoin** [comment]
@Xecute0101 what do you think about this topic?

**Comment by Xecute0101** [comment]
Comparing the text outputs from the integration test and the transfer test, the transfer test seems to includes tests of integration test. If it is in that case, I think we can remove the integration test.

**Comment by speqtr** [comment]
@Xecute0101 
Both integration and transfer tests share the same code base (using `IntegrationTestLib`), so by removing `IntegrationTestLin` we will also remove `IntegrationTests` and `TransferTests`.

**Comment by speqtr** [comment]
@qwertycoin-org and @Xecute0101 do you agree that we should remove the tests that were never used (`IntegrationTestLib`, `IntegrationTests`, `TransferTests`)? Or do you think that there is a reason to keep and try to fix those tests?

**Comment by Xecute0101** [comment]
Removing them is fine with me.

**Comment by Qwertycoin** [comment]
Yes, let's delete these never used tests.

**Comment by speqtr** [comment]
OK, cool! Thank you for your replies 🙂

Never used tests will be removed in one of the next commits.

**Comment by speqtr** [comment]
Updated stats:
1. **CoreTests** completes in 15 minutes, contains 15 broken/disabled tests;
2. **UnitTests** completes in 20 minutes, contains 50+ broken/disabled tests.

**Comment by speqtr** [comment]
It looks like Travis CI has a limitation of 50 minutes per job (not 2 hours as we discussed before). All the latest builds with enabled tests were interrupted at 50 minutes with the following error message:

> The job exceeded the maximum time limit for jobs, and has been terminated.

I'll try to enable parallel testing with at least 2 parallel jobs. Hope it will help.

cc @qwertycoin-org @Xecute0101

**Comment by speqtr** [comment]
NOTE: Also we need to find a way to make tests less verbose, so the build log won't exceed maximum amount of lines on AppVeyor CI and Travis CI.

**Comment by speqtr** [comment]
@Xecute0101 @qwertycoin-org 
`37.92%` is a code-coverage number that we get after enabling all currently working tests.

**Comment by nnpanda** [comment]
~38% coverage ouch. Yes we will beaten that with future improvements

**Comment by Xecute0101** [comment]
Okay. Let's finish up this part of codcov + baseline test coverage implementation. We have other pending tasks.

**Comment by speqtr** [comment]
@Xecute0101 you referrenced incorrect GitHub username in your comment 🙂
My username is @speqtr (with lowercase `s` and `q` instead of `c`).

**Comment by speqtr** [comment]
@qwertycoin-org @Xecute0101 I can confirm that this PR is ready to be merged.

**Comment by speqtr** [comment]
@qwertycoin-org Please, rerun CI builds for master branch. It seems that one of the macOS build jobs ran out of time.

**Comment by Qwertycoin** [comment]
It's building now.

**Comment by Qwertycoin** [comment]
@speqtr have rerun CI builds twice. It still throws an error macOS debug

**Comment by speqtr** [comment]
@qwertycoin-org I see. And both time it runs into 50 minutes limitation of Travis CI. I will look into tests that we can temporary disable in order to fit into those 50 minutes.

**Comment by speqtr** [comment]
@qwertycoin-org I'll open another PR with some more improvements + we will disable some test to make sure that CI won't run into Travis CI build time limitations.

**Pull request merged**
