### PR TITLE
Updated block reward formula

### PR DESCRIPTION
**Pull request by speqtr**
More details about new formula can be found in issue #78.

### CODE REVIEW

**Comment by speqtr** [comment]
@nnian please, review and merge 🙂

**Comment by nnian** [comment]
Okay, I thought it would be easy to add the height. I think we have to set an update height, so that all users have enough time to download the new software to be ready when the Reward system changes. 

Maybe: 
`const uint32_t UPGRADE_HEIGHT_REWARD_SCHEME = 400000;`

```
if (height < CryptoNote::parameters::UPGRADE_HEIGHT_REWARD_SCHEME) {
        reward = penalizedBaseReward + penalizedFee;
 } else {
        reward = (penalizedBaseReward + penalizedFee) * consistency;
}
```

Or any other solutions?

**Comment by nnian** [comment]
@speqtr I had to undo this PR then until we discussed this update scenario. I thought it would be just a matter of a few minutes to add this update height, but that was not the case. @exploshot

**Comment by zawy12** [comment]
I've done a lot of work on this type of idea.  See my **[TSA article](https://github.com/zawy12/difficulty-algorithms/issues/36)**  Here's the simple version of what should be done. Either difficulty or reward should be changed, but not both because if done simply it will be a squared factor on miner motivation that will cause  emission rate to speed up or cause oscillations due to smart mining coming and going to take max profit with fewer losses.  The equations below should stay close to target solvetime and target coin emission rate automatically without doing anything else (which could mess something up). Theoretically there is no difference between increasing difficulty and lowering rewards in terms of miner motivation. 

```
// Linearly increase reward from 1/1.3 = 0.77 for 
// solvetime = 1 second to 2x for solvetimes > 4x target

SolvetimeRatio = (this_timestamp - previous_timestamp) / TargetSolvetime;
reward = BaseReward / max(0.3, (1.3 - 0.2*SolvetimeRatio);
```
But make sure out of sequence timestamps are handled correctly:
```
// Safely handle out-of-sequence timestamps
if ( timestamps[i]  >= previous_timestamp ) {   this_timestamp = timestamps[i];  } 
else {  this_timestamp = previous_timestamp+1;   }
```

Or change difficulty (my preference) to decrease from 1.3 to 0.3 as solvetime goes from 1 to 5x target.
```
Difficulty = NormalDifficulty * max(0.3, (1.3 - 0.2*SolvetimeRatio);
```

**Pull request merged**
