### PR TITLE
Miscellaneous project improvements

### PR DESCRIPTION
**Pull request by speqtr**
Main goal of this PR is to simplify import process of this project into `qwertycoin-gui` and `qwertycoin-zero`.

### CODE REVIEW

**Comment by speqtr** [comment]
@qwertycoin-org This PR can be merge once you see that all CI scripts are "green" 🙂

**Comment by speqtr** [comment]
@qwertycoin-org Could you please push new tag (`5.2.0` or `5.1.4`) to `master` branch after merging this PR? I need this to configure `qwertycoin` imports in `qwertycoin-gui` and `qwertycoin-zero` repositories.

**Comment by Qwertycoin** [comment]
@speqtr yes sure we can bump the version. 
And btw there is a little issue with version code or isn't it?
Old: 5.1.3.3000 (6db7f2b-g6db7f2b)
After your last PR: 5.1.3.3000 (5.1.3) Was that intended?

**Comment by speqtr** [comment]
@qwertycoin-org This change was not intended. Please, open an issue and assign it to me. I'll fix it in a separate PR after this one is merged.

**Pull request merged**
