### PR TITLE
Add backward-cpp from Google for stack traces on abnormal exit codes

### PR DESCRIPTION
**Pull request by who-biz**
See here for an explanation of what this module does: https://github.com/bombela/backward-cpp

Note that for full stack trace inforrmation, the binaries will need build as follows:

`mkdir build && cd build && cmake -DBUILD_ALL:BOOL=TRUE -DCMAKE_BUILD_TYPE=Debug ..`

Limited info is still output, when binaries are built without debugging symbols.

### CODE REVIEW

**Comment by who-biz** [comment]
Sorry, forgot to include the `libbfd-dev` and `libdwarf-dev` packages in `CMakeLists.txt`

**Comment by who-biz** [comment]
https://github.com/qwertycoin-org/qwertycoin/compare/b56c3f1f1f629a5b81b9c8ccf93510fc43c54466..70551716ecf99176f363ce0a08e5aff4235323ae

As of the force push above ^ `backward-cpp` will only build for debug builds, and not release builds.

**Comment by Xecute0101** [comment]
> https://github.com/qwertycoin-org/qwertycoin/compare/b56c3f1f1f629a5b81b9c8ccf93510fc43c54466..70551716ecf99176f363ce0a08e5aff4235323ae
> 
> As of the force push above ^ `backward-cpp` will only build for debug builds, and not release builds, so as to avoid additional dependencies.

So do we need to modify travis and appveyor script to include a conditional statement for such case?

**Comment by who-biz** [comment]
>So do we need to modify travis and appveyor script to include a conditional statement for such case?

Sounds like that would be correct.  I've only used Travis a couple of times, though, and never in the role of actually writing the scripts. So maybe someone else could add those? If it isn't too much trouble.  

Otherwise... never a bad time to learn, I suppose.

**Comment by nnian** [comment]
That's the next open PR what should we do now?

**Comment by speqtr** [comment]
@exploshot @nnian @who-biz @Xecute0101, a couple of notes:
1. Does it work on all Qwertycoin-supported platforms (Linux, macOS, Windows, Android)? Or is it Linux-only feature?
2. For release builds we can integrate it using `RelWithDebInfo` build type;
3. Did you consider [Google Breakpad](https://chromium.googlesource.com/breakpad/breakpad) as an alternative for `backward.cpp`? While `backward.cpp` looks like more of a developer-only feature, `Google Breakpad` can be shipped with production binaries and help users to submit detailed crash reports.
4. Did you consider [Boost.Stacktrace](https://www.boost.org/doc/libs/1_71_0/doc/html/stacktrace.html) as an alternative? We are already heavily depend on Boost libraries and connecting one more library from Boost framework won't be an issue, while `backward-cpp` adds three new dependencies: `backward-cpp`, `libbfd` and `libdw`.

**Comment by Xecute0101** [comment]
@who-biz Is this feature required for LMDB implementation?

**Comment by who-biz** [comment]
@speqtr

1.) Not sure about all platforms.  Have only tested on Linux. 
2.) That sounds like a good solution. 
3/4.) Have not considered alternatives.  Only went with this option out of familiarity and need for a solution when I was debugging LMDB.  If you feel a different solution better suits the broader needs of QWC, I'm on board with that.

One note: Upon further testing, it appears that `libdwarf` is actually not necessary in the presence of the `binutils-dev` package.  Everything functions as it should without it. I'll submit a `force-push` here in just a moment to remove that package from dependencies.

**Comment by who-biz** [comment]
> @who-biz Is this feature required for LMDB implementation?

Not necessary, no.  Extremely helpful in situations where a `SIGSEGV` or similar abnormal exit code occurs, however.  Normally, no information is printed to `stdout` in these situations.  With `
`backward`, you get a full stack trace to the exact line where the error is occurring.

**Comment by Xecute0101** [comment]
@speqtr 

1) https://github.com/bombela/backward-cpp/issues/50

**Comment by speqtr** [comment]
@Xecute0101 

> 2. Release with Debug Information for official releases? Is this necessary?

We don't need to distribute this debug symbols publicly (users don't need to download them), we just need to store them somewhere in the cloud (or locally), so whenever user submits "crash report" we will be able to use those debug symbols to decode symbols that will be sent with "crash report" and figure out exact place in code where program did crash on user's machine.

NOTE: this workflow works for Google Breakpad, I'm not sure about `backward-cpp`.

**Comment by speqtr** [comment]
Google Breakpad support all major platforms (Linux, macOS, Windows, Android and iOS).

**Comment by Xecute0101** [comment]
@speqtr 

So, can you make your proposal in this?

1. Breakpad for crash reporting for issues found during customer's operation and/or
2. Boost.stacktrace for developer's debugging?

**Comment by speqtr** [comment]
@Xecute0101

1. for customer's crash reporting feature we can integrate Google Breakpad;
2. for development pusposes (honestly) I don't see any particular reason to integrate any lib, since running application in debug mode in any modern IDE will give you the same (or almost the same) result.

**Comment by who-biz** [comment]
`2. for development pusposes (honestly) I don't see any particular reason to integrate any lib, since running application in debug mode in any modern IDE will give you the same (or almost the same) result.`

Respectfully, I am not aware of any IDE that prints detailed info on *crashes* as well as tracing up the call stack to find and annotate (automatically) the precise line where a crash is occurring. But, if you've found one don't hesitate to correct me.

**Comment by speqtr** [comment]
@who-biz 

CLion, Qt Creator, MSVC, etc. There are plenty of them.

**Comment by exploshot** [comment]
The most time i'm using VSCode or CLion but mostly VSCode

**Comment by speqtr** [comment]
@exploshot

VSCode in the current state is more like "advanced text editor" than fully featured IDE. So this debugging feature may not be available in VSCode.

**Comment by speqtr** [comment]
Further updated will be available in PR #123.

@exploshot @nnian should we close this PR since replacement for this feature is available in another PR?

**Comment by nnian** [comment]
Further updated will be available in PR #123.

**Pull request closed without merging**
