### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ranso73**
Add node 86.142.25.119

### CODE REVIEW

**Comment by zeilercd** [comment]
add my node please :)
http://72.201.215.202:8196 or http://72.201.215.202:8197 (not sure which one you need?)
tested the feeaddress and get info and all ok and working
thank you :)

**Comment by neppers2** [comment]
Please add node: 91.194.90.163:8197

**Comment by qwertycoin-org** [comment]
@ranso73 your node seems to be offline.

 86.142.25.119:8197/getinfo

**Comment by qwertycoin-org** [comment]
> 
> 
> Please add node: 91.194.90.163:8197

Your Node is added here: https://explorer.qwertycoin.org/#network

**Pull request closed without merging**
