### PR TITLE
Improved Android platform support

### PR DESCRIPTION
**Pull request by speqtr**
List of improvements:
- [x] improved build time on AppVeyor CI;
- [x] fixed git version detection;
- [x] enabled Android build on Travis Ci;
- [x] added platform files for Android under `src/Platform/Android/System`.

### CODE REVIEW

**Comment by speqtr** [comment]
Cmake behavior is slightly weird on Windows. It properly detects cache for dependencies (like Boost), but for some reasons decides to ignore it.

**Comment by speqtr** [comment]
One of the commits in this PR fixed cmake warnings whentrying to read project version from git tag.

**Comment by qwertycoin-org** [comment]
I am waiting and looking forward to your commits =)

**Comment by speqtr** [comment]
Thanks @qwertycoin-org 🙂 I prepared a lot of things for this PR.

But at the moment I'm a bit confused with the way Boost is installed on AppVeyor CI and can't figure out what is causing `cmake` errors when `find_package(Boost ...)` is called.

**Comment by speqtr** [comment]
Replaced `"DIAVIK"` with `"@VERSION@"` in `src/version.h.in`.

**Comment by speqtr** [comment]
@qwertycoin-org FYI, CMake (from MSVC toolchain) is often one step behind Boost.

It is possible to work around this with [simple hack from Boost.GIL](https://github.com/boostorg/gil/blob/develop/CMakeLists.txt#L114-L119):
```
# Latest FindBoost.cmake has likely been updated to detect Boost version not yet released
if (NOT EXISTS "${CMAKE_BINARY_DIR}/cmake/FindBoost.cmake")
  message(STATUS "Downloading FindBoost.cmake from https://gitlab.kitware.com/cmake/ master branch")
  file(DOWNLOAD
    "https://gitlab.kitware.com/cmake/cmake/raw/master/Modules/FindBoost.cmake"
    "${CMAKE_BINARY_DIR}/cmake/FindBoost.cmake")
endif()
list(INSERT CMAKE_MODULE_PATH 0 ${CMAKE_BINARY_DIR}/cmake)
```

I decided to simplify this "hack" and directly add latest `FindBoost.cmake` version into `cmake/find` folder.

**Comment by speqtr** [comment]
After a few updates/tweaks build time on AppVeyor CI went down from 45-60 minutes to 8-10 minutes.

**Comment by speqtr** [comment]
Next up is Android build on Travis CI... 🙂

**Comment by speqtr** [comment]
Done! Can be merged 🙂

cc @qwertycoin-org

**Comment by qwertycoin-org** [comment]
Perfect! Good work
I think the Android platform will bring us many benefits.

**Comment by speqtr** [comment]
> I think the Android platform will bring us many benefits.

Me too 🙂

**Pull request merged**
