### PR TITLE
Enable debug mode and code coverage for CI builds

### PR DESCRIPTION
**Pull request by speqtr**
`!WARNING!` Please, don't merge. I'll post a message once PR is ready to be merged.

TODO:
- [x] Update Travis CI configuration;
- [x] Enable "Debug" build for Android;
- [x] Enable "Debug" build for Linux;
- [x] Enable "Debug" build for macOS;
- [x] Added `codecov` external lib for code-coverage configuration (on supported platforms);
- [x] Enabled code-coverage settings for each library;
- [x] Run `CryptoTests` with `ctest` to generate minimal coverage info;
- [x] Enable code coverage report upload to codecov.io

NOTE: Additionally I added `.clang-format` file with Qt C++ Code Style settings. It's better to get it merged into `master` early, so all of us can start using it as early as possible.

### CODE REVIEW

**Comment by speqtr** [comment]
**NOTE:** In order to get coverage info with `lcov` tool it is required to run tests with `ctest` first.

Within the scope of this PR I will enable Travis CI to run `CryptoTests` target to get minimal amount of coverage info for `codecov.io`.

All broken tests will be fixed and enabled to run on CI builds within the scope of a separate PR.

**Comment by Qwertycoin** [comment]
@speqtr 
the codecov Token is already added to the travis (and appveyor) environment variables.

`CODECOV_TOKEN="abcdefgh-aaaa-bbbb-cccc-8b99cb66f300"`

I think we need this for succesful codecov upload or not?

**Comment by speqtr** [comment]
@qwertycoin-org

According to the codecov.io docs Travis CI should be able to upload code-coverage results without any additional tokens. I will re-confirm this information later today, once I enable code-coverage report upload on Travis CI.

**Comment by Qwertycoin** [comment]
@speqtr 
Okay sounds great.

**Comment by speqtr** [comment]
First coverage reports are available 🙂
Can be found here: https://codecov.io/gh/qwertycoin-org/qwertycoin
Once merged to master, the "diff coverage" will become available for future commits.

**Comment by speqtr** [comment]
@qwertycoin-org Please, merge this PR once you see that all builds are "green" 🙂

**Pull request merged**
