### PR TITLE
Modernize cmake scripts

### PR DESCRIPTION
**Pull request by speqtr**
> WARNING: Please, don't close this PR until I post "Done. Can be merged."

Main goal of this PR is to modernize cmake script (use latest techniques for configuring, building and packaging cmake-based projects).

Dependency managment:
- [x] Added custom cmake script for `Boost` dependency;
- [x] Removed redundant `external/gtest` dir;
- [x] Added custom cmake script for `GTes`t dependency;
- [x] Removed redundant `external/miniupnpc` dir;
- [x] Removed redundant cmake/FindMiniupnpc.cmake file
- [x] Added custom cmake script for `MiniUPnP::miniupnpc` dependency;
- [x] Updated project to support latest version of `MiniUPnP::miniupnpc` library;
- [x] Removed redundant `external/google` dir;
- [x] Added custom cmake script for `sparsehash::sparsehash` dependency;
- [x] Added custom cmake script for `Threads` dependency (cross-platform script for threads lib);

Fixes:
- [x] Fixed `upnpDiscover` call in `src/P2p/NetNode.cpp`;
- [x] Fixed windows includes order in `src/SimpleWallet/SimpleWallet.cpp`. Incorrect includes order in some cases may result into `error: re-definition of <whatever> struct/class/define`;
- [x] slightly improved `version.h` header generation;

Modernized:
- [x] modernized `CMakeLists.txt` script;
- [x] modernized `src/CMakeLists.txt`;
- [x] removed unneeded dependencies;
- [x] made dependencies of each lib/app clearer;
- [x] fixed linking step issues and warnings;

Tests:
- [x] Modernized cmake script for tests subdir;
- [x] Enabled tests build on Travis CI for macOS and Linux;
- [x] Enabled tests compilation on AppVeyor CI;
- [x] Resolved multiple compile time issues in `tests` subdir;

Artifacts packaging:
- [x] Added cmake scripts for cpack (artifacts packaging tool);
- [x] Configured `*.deb` artifact packaging for Linux;
- [x] Configured MSI installer artifact packaging for Windows;
- [x] Configured `*.tar.gz` artifacts packaging for Android and macOS (note: `apk` and `dmg` are useless for GUI-less applications);
- [x] Enabled artifacts packaging on AppVeyor CI (Windows);
- [x] Enabled artifacts packaging on Travis CI (Linux and macOS);

Additionally:
- [x] Removed usage of `file(GLOB ...)` macro from cmake scripts. Using this macro for `*.h` and `*.cpp` files is highly discouraged by everyone (including CMake core developers team);
- [x] Updated `cmake/polly` submodule;
- [x] Updated CI configs;
- [x] Fixed build instructions for Android in `README.md`.

### CODE REVIEW

**Comment by speqtr** [comment]
Resolving merge conflicts...

**Comment by speqtr** [comment]
Fixed merge conflicts. Now testing locally on Android, Linux, macOS and Windows to make sure that there are no regressions.

**Comment by qwertycoin-org** [comment]
> 
> 
> Resolving merge conflicts...

I'm sorry for your doubled work with your PR caused by my previous 5.0.2 Commit.

**Comment by speqtr** [comment]
@qwertycoin-org don't worry 🙂 
99% are fixed by now.
Just a few extra tweaks and all the CI scripts should turn green 👍

**Comment by speqtr** [comment]
OK, so Windows and macOS builds are green.

**Comment by speqtr** [comment]
Right now working on a small fix for `<tr1/functional>` include that should fix Android and Linux builds.

**Comment by qwertycoin-org** [comment]
fyi we had unexpected issues within the Blockchain. And commited a few lines. Only configuration stuff.

**Comment by speqtr** [comment]
@qwertycoin-org thanks for the update 🙂

**Comment by speqtr** [comment]
I already rebased my changes on top of those latest commits from `qwertycoin-org/qwertycoin/master`, so we won't have any merge conflicts while merging this branch.

**Comment by speqtr** [comment]
@qwertycoin-org Done. Can be merged.

**Pull request merged**
