### PR TITLE
Add exit fix

### PR DESCRIPTION
**Pull request by exploshot**
should fix https://github.com/qwertycoin-org/qwertycoin/issues/117

i've tested it with reverting the pr and tested some things.
This was the only way it doesn't crashed til now.

### CODE REVIEW

**Comment by speqtr** [comment]
In my opinion, instead of reverting `Qwertycoin::Constants::nullHash()` to `Qwertycoin::NULL_HASH` all over the code, it would be easier to just replace
```
Crypto::Hash Constants::nullHash()
{
    return Crypto::Hash({
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
    });
}
```
with something like
```
Crypto::Hash Constants::nullHash()
{
    return boost::value_initialized<Crypto::Hash>();
}
```
in a single file.

**Comment by exploshot** [comment]
@speqtr thats what i did at first but without success

**Comment by speqtr** [comment]
Hmmm... weird... could you please try the following thing then?
```
Crypto::Hash Constants::nullHash()
{
    const Crypto::Hash NULL_HASH = boost::value_initialized<Crypto::Hash>();
    return NULL_HASH;
}

```

**Comment by exploshot** [comment]
> Hmmm... weird... could you please try the following thing then?
> 
> ```
> Crypto::Hash Constants::nullHash()
> {
>     const Crypto::Hash NULL_HASH = boost::value_initialized<Crypto::Hash>();
>     return NULL_HASH;
> }
> ```

i did this too, no idea why this wasnt working, ive compared the Constants before and after this pr and saw that there was no "const", so i decided to implement this in another way, @nnian and i are actually working now on #120, thats why i closed the #119

**Comment by speqtr** [comment]
OK, so all further updates will be in #120, correct?

**Comment by exploshot** [comment]
Exactly

**Pull request closed without merging**
